### ISSUE TITLE
Make it work for negative numbers

### ISSUE THREAD

**Issue by yxor** [yxor/bruh-sort#1]
Right now bruh-sort can only handle positive integers, should make it support negative ones.

**Comment by Rudxain** [comment]
I think I know how to implement that feature. The basic algorithm is to find the most negative int, copy its absolute value, and add it to every single int that we want to sort (including the most negative)

I haven't read the C files yet, so I could be wrong.

I could write the C impl when I get some free time

**Comment by Rudxain** [comment]
Wait, I realized there's a problem with overflow. To avoid it, we must cast each int to its unsigned counterpart, at the same time we add the offset to each value. Rust's `unsigned_abs` comes to mind, so I know it must be possible to do this.

let `INT_MIN` be the most negative n-bit integer, let `INT_MAX` be the most positive, let `UINT_MAX` be the most positive unsigned int, and assume arbitrary precision:
```
abs(INT_MIN) == INT_MAX+1 // because two's complement
abs(INT_MIN) + INT_MAX == UINT_MAX // no overflow
// even in worst-case scenario
```
